"""AI 写作风格 Prompt 集合。

将原本集中在 ai_writer.py 中的 Prompt 常量拆分到独立风格文件，
本包统一导出，供 ai_writer.py 一行导入，保持调用方零改动。
"""

from ._red_lines import MILITARY_RED_LINES
from .baoming_shuo import SYSTEM_PROMPT_BAOMING_SHUO, BAOMING_SHUO_TOUTIE_PROMPT
from .jin_shuo import SYSTEM_PROMPT_JIN_SHUO, JIN_SHUO_TOUTIE_PROMPT
from .global_archive import SYSTEM_PROMPT_GLOBAL_ARCHIVE, GLOBAL_ARCHIVE_TOUTIE_PROMPT
from .story_narrative import SYSTEM_PROMPT_STORY_NARRATIVE, STORY_NARRATIVE_PROMPT
from .general import TOUTIE_PROMPT, ARTICLE_PROMPT, COVER_KEYWORD_PROMPT
from .humanize import HUMANIZE_SYSTEM_PROMPT, HUMANIZE_USER_PROMPT

__all__ = [
    "MILITARY_RED_LINES",
    "SYSTEM_PROMPT_BAOMING_SHUO", "BAOMING_SHUO_TOUTIE_PROMPT",
    "SYSTEM_PROMPT_JIN_SHUO", "JIN_SHUO_TOUTIE_PROMPT",
    "SYSTEM_PROMPT_GLOBAL_ARCHIVE", "GLOBAL_ARCHIVE_TOUTIE_PROMPT",
    "SYSTEM_PROMPT_STORY_NARRATIVE", "STORY_NARRATIVE_PROMPT",
    "TOUTIE_PROMPT", "ARTICLE_PROMPT", "COVER_KEYWORD_PROMPT",
    "HUMANIZE_SYSTEM_PROMPT", "HUMANIZE_USER_PROMPT",
]
