"""AI 写作风格 Prompt 集合。

将原本集中在 ai_writer.py 中的 Prompt 常量拆分到独立风格文件，
本包统一导出，供 ai_writer.py 一行导入，保持调用方零改动。
"""

from ._red_lines import MILITARY_RED_LINES
from .military import SYSTEM_PROMPT_MILITARY, MILITARY_TOUTIE_PROMPT
from .story_narrative import SYSTEM_PROMPT_STORY_NARRATIVE, STORY_NARRATIVE_PROMPT
from .sharp_commentary import SYSTEM_PROMPT_SHARP_COMMENTARY, SHARP_COMMENTARY_PROMPT
from .data_list import SYSTEM_PROMPT_DATA_LIST, DATA_LIST_PROMPT
from .flash_news import SYSTEM_PROMPT_FLASH_NEWS, FLASH_NEWS_PROMPT
from .discussion import SYSTEM_PROMPT_DISCUSSION, DISCUSSION_PROMPT
from .general import TOUTIE_PROMPT, ARTICLE_PROMPT, COVER_KEYWORD_PROMPT
from .humanize import HUMANIZE_SYSTEM_PROMPT, HUMANIZE_USER_PROMPT

__all__ = [
    "MILITARY_RED_LINES",
    "SYSTEM_PROMPT_MILITARY", "MILITARY_TOUTIE_PROMPT",
    "SYSTEM_PROMPT_STORY_NARRATIVE", "STORY_NARRATIVE_PROMPT",
    "SYSTEM_PROMPT_SHARP_COMMENTARY", "SHARP_COMMENTARY_PROMPT",
    "SYSTEM_PROMPT_DATA_LIST", "DATA_LIST_PROMPT",
    "SYSTEM_PROMPT_FLASH_NEWS", "FLASH_NEWS_PROMPT",
    "SYSTEM_PROMPT_DISCUSSION", "DISCUSSION_PROMPT",
    "TOUTIE_PROMPT", "ARTICLE_PROMPT", "COVER_KEYWORD_PROMPT",
    "HUMANIZE_SYSTEM_PROMPT", "HUMANIZE_USER_PROMPT",
]
